# Generated by Django 5.2.4 on 2025-11-15 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="hourly_wage",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
